name: Branch Pattern Example  

on:
  push:
    branches:
      - main                  

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display branch
        run: echo "Running on branch $GITHUB_REF"
