name: 04 - testing windows os output

on:
  push 
  workflow_dispatch:
  
jobs:
  echo-hello-world: 
    runs-on: 
      ubuntu-latest
    steps: 
	- run: echo "Hello World - Runner OS is $RUNNER_OS"	

  echo-say-good-bye:
    runs-on:
      windows-latest
    steps:
     - name: Shell	
     - shell: bash	
     - run: echo "Good bye - Runner OS is $RUNNER_OS"
