name: Branch Pattern Example 

on:
  push:
    branches:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Display branch
        run: "echo 'Branch: $(basename $GITHUB_REF)'"
