name: Create Issue Example

on:
  issues:
    types:
      - opened
      - closed


jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create an issue
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
            "title": "Automated Issue Title",
            "body": "This is test"
          }'
