#name: Test Specific Event Types

#on:
 # issues:
  #  types:
   #   - opened
    #  - closed

#jobs:
 # test-specific-events:
  #  runs-on: ubuntu-latest
   # steps:
    #  - name: Log Event Type
     #   run: |
      #    echo "Triggered by event: ${{ github.event_name }}"
       #   echo "Action type: ${{ github.event.action }}"
