name: Test Create Issue Job 

on:
  workflow_dispatch: # Allows manual triggering from the Actions tab

jobs:
  create-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Create Issue
        run: |
          curl -X POST https://api.github.com/repos/${{ github.repository }}/issues \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{
            "title": "Test Issue",
            "body": "This issue is created as a test from GitHub Actions."
          }'
