name: Run on Specific Path Change

on:
  push:
    paths:
      - "src/**"
  pull_request:
    paths:
      - "src/**"

jobs:
  path-change-job:
    runs-on: ubuntu-latest
    steps:
      - name: Show Changed Files
        run: |
          echo "Detecting changed files..."
          git diff --name-only ${{ github.event.before }} ${{ github.sha }}
